// Generated by gencpp from file vision_missions/center.msg
// DO NOT EDIT!


#ifndef VISION_MISSIONS_MESSAGE_CENTER_H
#define VISION_MISSIONS_MESSAGE_CENTER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_missions
{
template <class ContainerAllocator>
struct center_
{
  typedef center_<ContainerAllocator> Type;

  center_()
    : x(0.0)
    , y(0.0)
    , value(false)  {
    }
  center_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , value(false)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::vision_missions::center_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_missions::center_<ContainerAllocator> const> ConstPtr;

}; // struct center_

typedef ::vision_missions::center_<std::allocator<void> > center;

typedef boost::shared_ptr< ::vision_missions::center > centerPtr;
typedef boost::shared_ptr< ::vision_missions::center const> centerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_missions::center_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_missions::center_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_missions::center_<ContainerAllocator1> & lhs, const ::vision_missions::center_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_missions::center_<ContainerAllocator1> & lhs, const ::vision_missions::center_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_missions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_missions::center_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_missions::center_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_missions::center_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_missions::center_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_missions::center_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_missions::center_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_missions::center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8242b7d2c084ebc7b0621c9ba554c659";
  }

  static const char* value(const ::vision_missions::center_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8242b7d2c084ebc7ULL;
  static const uint64_t static_value2 = 0xb0621c9ba554c659ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_missions::center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_missions/center";
  }

  static const char* value(const ::vision_missions::center_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_missions::center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"bool value\n"
;
  }

  static const char* value(const ::vision_missions::center_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_missions::center_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct center_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_missions::center_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_missions::center_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MISSIONS_MESSAGE_CENTER_H
